CREATE TABLE "combatLog" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combatLog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"combatStateId" integer NOT NULL,
	"round" integer NOT NULL,
	"actorName" text NOT NULL,
	"actionType" varchar(20) NOT NULL,
	"targetName" text,
	"rollType" varchar(20),
	"rollResult" integer,
	"outcome" text,
	"damageDealt" integer,
	"narrative" text,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "combatState" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combatState_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"inCombat" integer DEFAULT 0 NOT NULL,
	"currentRound" integer DEFAULT 0 NOT NULL,
	"currentTurnIndex" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "combatState_sessionId_unique" UNIQUE("sessionId")
);
--> statement-breakpoint
CREATE TABLE "combatants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combatants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"combatStateId" integer NOT NULL,
	"name" text NOT NULL,
	"type" varchar(10) NOT NULL,
	"characterId" integer,
	"initiative" integer NOT NULL,
	"ac" integer NOT NULL,
	"hpCurrent" integer NOT NULL,
	"hpMax" integer NOT NULL,
	"attackBonus" integer,
	"damageFormula" text,
	"damageType" text,
	"specialAbilities" text,
	"position" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "initiativeBonus" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "attackBonus" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "damageFormula" text;--> statement-breakpoint
ALTER TABLE "userSettings" ADD COLUMN "characterGenerationPrompt" text;--> statement-breakpoint
ALTER TABLE "userSettings" ADD COLUMN "combatTurnPrompt" text;--> statement-breakpoint
ALTER TABLE "userSettings" ADD COLUMN "combatNarrationPrompt" text;--> statement-breakpoint
ALTER TABLE "userSettings" ADD COLUMN "combatSummaryPrompt" text;--> statement-breakpoint
ALTER TABLE "combatLog" ADD CONSTRAINT "combatLog_sessionId_sessions_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combatLog" ADD CONSTRAINT "combatLog_combatStateId_combatState_id_fk" FOREIGN KEY ("combatStateId") REFERENCES "public"."combatState"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combatState" ADD CONSTRAINT "combatState_sessionId_sessions_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combatants" ADD CONSTRAINT "combatants_sessionId_sessions_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combatants" ADD CONSTRAINT "combatants_combatStateId_combatState_id_fk" FOREIGN KEY ("combatStateId") REFERENCES "public"."combatState"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "combatants" ADD CONSTRAINT "combatants_characterId_characters_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."characters"("id") ON DELETE no action ON UPDATE no action;